eslint and prettier setup
boqnd/sliding-puzzle pull request #11
Opened 2022-12-05 17:17 UTC by boqnd

Rules should be discussed and added.

2022-12-05 17:40 UTC, Ilia-tod29 approved these changes

2022-12-05 17:54 UTC, GritzMaze requested changes

2022-12-05 17:54 UTC, GritzMaze commented on server/.eslintrc.json
> +  "rules": {}
Can you put the rules, so when husky is set up it should not allow to be pushed with errors.
```
"rules": {
        "indent": 
        [
            "error",
            2
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ],
        "no-console": [
            "error"
        ],
}
```

2022-12-05 18:05 UTC, boqnd commented on server/.eslintrc.json
> +  "rules": {}
no-console will throw error on every console.log. Do we want that?

2022-12-05 18:20 UTC, GritzMaze commented on server/.eslintrc.json
> +  "rules": {}
Yeah, maybe we if add a logging tool like winston. It is not necessary right now

2022-12-06 09:28 UTC, Ilia-tod29 approved these changes

2022-12-06 15:23 UTC, GritzMaze approved these changes

2022-12-06 15:23 UTC, merged